"""new dt

Revision ID: b01ae96b9c19
Revises: 95be60c69e1b
Create Date: 2026-05-22 12:05:19.272628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b01ae96b9c19'
down_revision: Union[str, Sequence[str], None] = '95be60c69e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('timeline_members', 'timeline_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('timeline_members', 'member_permission',
               existing_type=postgresql.ENUM('DEFAULT', 'CHANGE', name='memberpermission'),
               nullable=False)
    op.alter_column('timeline_members', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('unique_timeline_member', 'timeline_members', ['timeline_id', 'member_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_timeline_member', 'timeline_members', type_='unique')
    op.alter_column('timeline_members', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('timeline_members', 'member_permission',
               existing_type=postgresql.ENUM('DEFAULT', 'CHANGE', name='memberpermission'),
               nullable=True)
    op.alter_column('timeline_members', 'timeline_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
